[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "deepaneseg"
version = "0.1.0"
description = "Detection of brain aneurysms from MRA with a 3D U-Net and an efficient data strategy (DALI @ MICCAI 2021)"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Youssef Assis" }]
dependencies = [
    "numpy",
    "scipy",
    "scikit-image",
    "scikit-learn",
    "pandas",
    "nibabel",
    "SimpleITK",
    "torch",
    "tensorboard",
    "tqdm",
    "prefetch_generator",
]

[project.optional-dependencies]
dev = ["pytest", "ruff"]

[tool.setuptools.packages.find]
include = ["deepaneseg*"]
